"""
photo_story.py — Generates a captioned photo story PDF.

For each family photo, displays the image (if available) alongside a warm
caption generated by the agent, to be read aloud by the caregiver.

Accessibility: captions use 18pt minimum font per spec.
"""

from pathlib import Path
from typing import Optional

from fpdf import FPDF

_UNICODE_MAP = str.maketrans({
    "\u2014": "--", "\u2013": "-", "\u2018": "'", "\u2019": "'",
    "\u201c": '"',  "\u201d": '"', "\u2026": "...", "\u2022": "-",
    "\u00a0": " ",
})

def _safe(text: str) -> str:
    return text.translate(_UNICODE_MAP).encode("latin-1", errors="replace").decode("latin-1")


def _try_embed_image(pdf: FPDF, image_path: Path, x: float, y: float, max_w: float, max_h: float) -> Optional[float]:
    """
    Attempt to embed an image. Returns the height used, or None on failure.
    Reads the image fully into a BytesIO buffer before calling pdf.image so
    the file handle is released before fpdf2 tries to access it (avoids
    Windows file-lock conflicts).
    """
    try:
        import io
        from PIL import Image

        with Image.open(image_path) as img:
            img.load()  # force full read into memory
            orig_w, orig_h = img.size
            if img.mode not in ("RGB", "L"):
                img = img.convert("RGB")
            ratio = min(max_w / orig_w, max_h / orig_h)
            display_w = orig_w * ratio
            display_h = orig_h * ratio
            buf = io.BytesIO()
            img.save(buf, "JPEG", quality=90)
            buf.seek(0)

        # PIL file handle is now fully closed — safe to pass buffer to fpdf2
        pdf.image(buf, x=x, y=y, w=display_w, h=display_h)
        return display_h

    except Exception:
        return None


def generate_photo_story_pdf(
    captions: list,
    profile: dict,
    photos_dir: Path,
    output_path: Path,
) -> Path:
    """
    Generate the photo story PDF.

    captions: list of {filename, caption} from the agent.
    photos_dir: directory where patient photos are stored.
    """
    patient_name = profile["name"]
    patient_first = patient_name.split()[0]

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Cover page ───────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    pdf.set_font("Helvetica", style="I", size=9)
    pdf.set_text_color(180, 160, 140)
    pdf.cell(0, 8, "Hearth -- a memory companion", ln=True, align="R")
    pdf.ln(30)

    pdf.set_font("Helvetica", style="B", size=28)
    pdf.set_text_color(60, 40, 20)
    pdf.cell(0, 14, _safe(f"{patient_first}'s"), ln=True, align="C")
    pdf.set_font("Helvetica", style="", size=28)
    pdf.cell(0, 14, "Photo Story", ln=True, align="C")

    pdf.ln(8)
    pdf.set_font("Helvetica", style="I", size=13)
    pdf.set_text_color(130, 100, 80)
    pdf.cell(0, 10, "Memories shared by family, with love.", ln=True, align="C")

    pdf.ln(20)
    pdf.set_draw_color(200, 180, 160)
    pdf.set_line_width(0.5)
    pdf.line(40, pdf.get_y(), 170, pdf.get_y())

    pdf.ln(18)
    pdf.set_font("Helvetica", style="I", size=11)
    pdf.set_text_color(140, 110, 90)
    pdf.multi_cell(
        0,
        8,
        _safe("A caregiver's guide: Show each photo gently. Read the caption aloud. "
              "Pause. Let the memory land. There is no rush."),
        align="C",
    )

    # ── One page per photo ───────────────────────────────────────────────────
    for item in captions:
        filename = item.get("filename", "")
        caption = item.get("caption", "")

        pdf.add_page()
        pdf.set_margins(20, 20, 20)

        # Page top label
        pdf.set_font("Helvetica", style="I", size=9)
        pdf.set_text_color(180, 160, 140)
        pdf.cell(0, 6, _safe(f"{patient_name} -- Photo Story"), ln=True, align="R")
        pdf.ln(4)

        # Try to embed the actual photo
        img_path = photos_dir / filename
        img_used = False

        if img_path.exists():
            used_h = _try_embed_image(
                pdf,
                img_path,
                x=20,
                y=pdf.get_y(),
                max_w=170,
                max_h=110,
            )
            if used_h is not None:
                pdf.set_y(pdf.get_y() + used_h + 6)
                img_used = True

        if not img_used:
            # Placeholder box with filename
            box_y = pdf.get_y()
            pdf.set_draw_color(210, 190, 170)
            pdf.set_fill_color(248, 244, 240)
            pdf.rect(20, box_y, 170, 80, style="FD")

            pdf.set_y(box_y + 28)
            pdf.set_font("Helvetica", style="I", size=11)
            pdf.set_text_color(160, 130, 110)
            pdf.cell(0, 8, _safe(f"[ {filename} ]"), ln=True, align="C")
            pdf.set_font("Helvetica", style="I", size=9)
            pdf.cell(0, 6, "Place photo here", ln=True, align="C")
            pdf.set_y(box_y + 86)

        pdf.ln(6)

        # Photo filename in small text
        pdf.set_font("Helvetica", style="I", size=9)
        pdf.set_text_color(170, 150, 130)
        pdf.cell(0, 5, _safe(filename), ln=True, align="C")
        pdf.ln(8)

        # Caption — large, readable font (18pt minimum per spec)
        pdf.set_font("Helvetica", size=18)
        pdf.set_text_color(40, 30, 20)
        pdf.multi_cell(0, 10, _safe(caption))

        # Bottom rule
        pdf.ln(8)
        if pdf.get_y() < 250:
            pdf.set_draw_color(210, 190, 170)
            pdf.set_line_width(0.3)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())

    # ── Back page ────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_margins(20, 20, 20)
    pdf.ln(80)
    pdf.set_font("Helvetica", style="I", size=14)
    pdf.set_text_color(150, 120, 100)
    pdf.cell(0, 10, "Every photo holds a world.", ln=True, align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", style="I", size=10)
    pdf.set_text_color(180, 160, 140)
    pdf.cell(0, 7, "Generated with love by Hearth.", ln=True, align="C")

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))
    return output_path
