"""
voice_generator.py — ElevenLabs voice synthesis module.

Clones the family member's voice from a submitted sample and synthesizes
the agent-generated script in that cloned voice.

Graceful fallback: if ELEVENLABS_API_KEY is missing or synthesis fails,
saves the script as a .txt file with playback instructions instead.
"""

import os
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

load_dotenv()


def _has_elevenlabs_key() -> bool:
    key = os.getenv("ELEVENLABS_API_KEY", "").strip()
    return bool(key)


def _find_voice_sample(voice_samples_dir: Path, memories: list) -> Optional[Path]:
    """Find the first voice sample file referenced in memories."""
    for m in memories:
        vsf = m.get("voice_sample_file")
        if vsf:
            candidate = voice_samples_dir / vsf
            if candidate.exists():
                return candidate

    # Fallback: any .mp3 in voice_samples dir
    if voice_samples_dir.exists():
        for f in voice_samples_dir.iterdir():
            if f.suffix.lower() in {".mp3", ".wav", ".m4a", ".ogg"}:
                return f

    return None


def _save_text_fallback(script: str, output_path: Path, family_member: str) -> Path:
    """Save script as text with instructions when ElevenLabs is unavailable."""
    txt_path = output_path.with_suffix(".txt")
    txt_path.parent.mkdir(parents=True, exist_ok=True)

    sep = "-" * 50
    content = "\n".join([
        "HEARTH -- VOICE MESSAGE SCRIPT",
        "==============================",
        "",
        f"From: {family_member}",
        "",
        sep,
        "",
        script.strip(),
        "",
        sep,
        "",
        "PLAYBACK INSTRUCTIONS:",
        "This script was generated by Hearth but could not be synthesized as audio",
        "because no ElevenLabs API key was provided.",
        "",
        "To create audio:",
        "  1. Set ELEVENLABS_API_KEY in your .env file and re-run lucid_now, OR",
        "  2. Record a family member reading this script (60-80 words, ~30 seconds), OR",
        "  3. Use any text-to-speech tool to generate audio from this script.",
        "",
        "The script above is written to be read aloud in a warm, personal voice.",
        "",
    ])

    txt_path.write_text(content, encoding="utf-8")
    return txt_path


def generate_voice_message(
    script: str,
    profile: dict,
    voice_samples_dir: Path,
    memories: list,
    output_path: Path,
) -> tuple[Path, bool]:
    """
    Synthesize the voice message.

    Returns (output_path, synthesized_as_audio).
    - synthesized_as_audio=True: .mp3 was created via ElevenLabs
    - synthesized_as_audio=False: .txt fallback was created
    """
    family_member = profile["primary_family_contact"]
    patient_first = profile["name"].split()[0]

    if not _has_elevenlabs_key():
        print("  ElevenLabs API key not set — saving voice script as text file.")
        txt_path = _save_text_fallback(script, output_path, family_member)
        return txt_path, False

    try:
        from elevenlabs.client import ElevenLabs
        from elevenlabs import VoiceSettings

        client = ElevenLabs(api_key=os.getenv("ELEVENLABS_API_KEY"))

        voice_sample = _find_voice_sample(voice_samples_dir, memories)

        if voice_sample is None:
            print("  No voice sample found — saving voice script as text file.")
            txt_path = _save_text_fallback(script, output_path, family_member)
            return txt_path, False

        print(f"  Cloning voice from: {voice_sample.name}")

        # Instant Voice Cloning — creates a temporary voice from the sample
        with open(voice_sample, "rb") as f:
            cloned_voice = client.voices.ivc.create(
                name=f"{family_member} (Hearth clone)",
                files=[f],
                description=f"Voice clone for Hearth — {family_member}",
            )

        voice_id = cloned_voice.voice_id
        print(f"  Voice cloned. Synthesizing message for {patient_first}...")

        # Synthesize speech
        audio_generator = client.text_to_speech.convert(
            voice_id=voice_id,
            text=script,
            model_id="eleven_multilingual_v2",
            voice_settings=VoiceSettings(
                stability=0.6,
                similarity_boost=0.85,
                style=0.3,
                use_speaker_boost=True,
            ),
            output_format="mp3_44100_128",
        )

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, "wb") as f:
            for chunk in audio_generator:
                if chunk:
                    f.write(chunk)

        # Clean up the cloned voice to avoid cluttering ElevenLabs account
        try:
            client.voices.delete(voice_id)
        except Exception:
            pass

        return output_path, True

    except ImportError:
        print("  elevenlabs package not installed — saving voice script as text file.")
        txt_path = _save_text_fallback(script, output_path, family_member)
        return txt_path, False

    except Exception as e:
        print(f"  ElevenLabs error ({e}) — saving voice script as text file.")
        txt_path = _save_text_fallback(script, output_path, family_member)
        return txt_path, False
